// COMPONENT
import { Header } from '@/components/header'
import { Sidebar } from '@/components/sidebar'
import { Textarea } from '@/components/ui/textarea'

export default function Home() {
  return (
    <div className="grid min-h-screen grid-rows-root gap-4 pb-4">
      <Header />

      <main className="grid px-4 md:grid-cols-main md:gap-8">
        <section className="grid gap-4 md:gap-8">
          <Textarea
            placeholder="Include AI prompt here..."
            className="resize-none bg-soft-violet leading-relaxed"
          />
          <Textarea
            placeholder="Result generated by AI..."
            className="resize-none bg-lime leading-relaxed"
          />
        </section>

        <Sidebar />
      </main>
    </div>
  )
}
