'use client'

// DEPENDENCY
import { useAi } from '@/hooks/useAi'

// COMPONENT
import { Textarea } from '@/components/ui/textarea'

export function AiResponse() {
  const { template, completion, handleTemplateChange } = useAi()

  return (
    <>
      <Textarea
        placeholder="Include AI prompt here..."
        className="resize-none bg-soft-violet leading-relaxed"
        value={template ?? ''}
        onChange={handleTemplateChange}
      />
      <Textarea
        placeholder="Result generated by AI..."
        className="resize-none bg-lime leading-relaxed"
        value={completion}
      />
    </>
  )
}
